### ISSUE TITLE
Copy affordance broken

### ISSUE THREAD

**Issue by wxmerkt** [RobotLocomotion/director#391]
```
copyAffordance
    aff = robotSystem.affordanceManager.newAffordanceFromDescription(desc)
AttributeError: 'FieldContainer' object has no attribute 'affordanceManager'
Traceback (most recent call last):
  File "/home/wxm/dev/oh-distro-private/software/build/lib/python2.7/dist-packages/director/robotviewbehaviors.py", line 490, in copyAffordance
    aff = robotSystem.affordanceManager.newAffordanceFromDescription(desc)
AttributeError: 'FieldContainer' object has no attribute 'affordanceManager'
Traceback (most recent call last):
  File "/home/wxm/dev/oh-distro-private/software/build/lib/python2.7/dist-packages/director/robotviewbehaviors.py", line 490, in copyAffordance
    aff = robotSystem.affordanceManager.newAffordanceFromDescription(desc)
AttributeError: 'FieldContainer' object has no attribute 'affordanceManager'
```

**Comment by patmarion** [comment]
thanks for reporting.   I think this can be resolved by adding 'Affordances' to the list of declared dependencies of 'RobotViewBehaviors' in robotsystem.py

**Comment by patmarion** [comment]
here https://github.com/RobotLocomotion/director/blob/master/src/python/director/robotsystem.py#L36
