### ISSUE TITLE
AttributeError: 'module' object has no attribute 'viewer_load_robot_t'

### ISSUE THREAD

**Issue by AlameluThinnappan** [RobotLocomotion/director#605]
Visualizer fails with the following error when I try to run it :Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alamelu/director/build/install/lib/python2.7/site-packages/director/drakevisualizerapp.py", line 36, in main
    applicationName=appName)
  File "/home/alamelu/director/build/install/lib/python2.7/site-packages/director/componentgraph.py", line 148, in construct
    self.initComponent(name, defaultFields)
  File "/home/alamelu/director/build/install/lib/python2.7/site-packages/director/componentgraph.py", line 164, in initComponent
    newFields = initFunction(inputFields)
  File "/home/alamelu/director/build/install/lib/python2.7/site-packages/director/mainwindowapp.py", line 455, in initDrakeVisualizer
    drakeVisualizer = drakevisualizer.DrakeVisualizer(fields.view)
  File "/home/alamelu/director/build/install/lib/python2.7/site-packages/director/drakevisualizer.py", line 320, in __init__
    self.enable()
  File "/home/alamelu/director/build/install/lib/python2.7/site-packages/director/drakevisualizer.py", line 345, in enable
    self.setEnabled(True)
  File "/home/alamelu/director/build/install/lib/python2.7/site-packages/director/drakevisualizer.py", line 340, in setEnabled
    self._addSubscribers()
  File "/home/alamelu/director/build/install/lib/python2.7/site-packages/director/drakevisualizer.py", line 324, in _addSubscribers
    self.subscribers.append(lcmUtils.addSubscriber('DRAKE_VIEWER_LOAD_ROBOT', lcmrl.viewer_load_robot_t, self.onViewerLoadRobot))
AttributeError: 'module' object has no attribute 'viewer_load_robot_t'
After compiling, I did enable LCM on the existing build according to #353
Any direction here will be great. Thanks!

**Comment by patmarion** [comment]
Is it possible that you have a conflicting version of libbot installed somewhere else?  Did you enable the USE_SYSTEM_LIBBOT variable when configuring director?

**Comment by patmarion** [comment]
It looks like you might be configuring wrong.  Please see the toplevel README for instructions.  It should look something like this:

```
cd director
mkdir build && cd build
cmake ../distro/superbuild
make
```

If you want, you can add `-DUSE_LCM=ON`.  You might also consider using precompiled binaries here:  https://bintray.com/patmarion/director/director/0.1.0-266-g071a233#files

Or possibly use another project like `spartan` or `labelfusion` which provide docker environments with director pre-installed.

**Comment by AlameluThinnappan** [comment]
Thank you!
I cleaned the existing build, built from source again with -DUSE_LCM=ON . It works now.
